version: '3'

services:
  mysql:
    image: mysql:5.7
    env_file: .env
    volumes:
      - ./mysql:/var/lib/mysql
  graphql:
    build: .
    env_file: .env
    links:
      - mysql
    ports:
      - '4444:4444'
    volumes:
      - ./:/code
